name: Setup Terraform
description: Install Terraform and run terraform init

runs:
  using: composite
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - name: Terraform Init
      shell: bash
      working-directory: terraform
      run: terraform init
